// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbt74DIcmq8lyzVNgAO0WD-hoTJLGmQuA',
    appId: '1:342229738257:web:65907eb535eb4c0662e2b0',
    messagingSenderId: '342229738257',
    projectId: 'delivery-app-first',
    authDomain: 'delivery-app-first.firebaseapp.com',
    storageBucket: 'delivery-app-first.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANuhcjdu8V9yBLFsS71dsa0RxCH1EThxI',
    appId: '1:342229738257:android:ba69c7b7d1de448262e2b0',
    messagingSenderId: '342229738257',
    projectId: 'delivery-app-first',
    storageBucket: 'delivery-app-first.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZgKyBojuuHPdBXS9FG65HdUXvKrqBrvQ',
    appId: '1:342229738257:ios:f39661687da2d57962e2b0',
    messagingSenderId: '342229738257',
    projectId: 'delivery-app-first',
    storageBucket: 'delivery-app-first.appspot.com',
    iosBundleId: 'com.example.pizzaDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZgKyBojuuHPdBXS9FG65HdUXvKrqBrvQ',
    appId: '1:342229738257:ios:f39661687da2d57962e2b0',
    messagingSenderId: '342229738257',
    projectId: 'delivery-app-first',
    storageBucket: 'delivery-app-first.appspot.com',
    iosBundleId: 'com.example.pizzaDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbt74DIcmq8lyzVNgAO0WD-hoTJLGmQuA',
    appId: '1:342229738257:web:f055c6d519216a2b62e2b0',
    messagingSenderId: '342229738257',
    projectId: 'delivery-app-first',
    authDomain: 'delivery-app-first.firebaseapp.com',
    storageBucket: 'delivery-app-first.appspot.com',
  );
}
